# Generated by Django 5.0.6 on 2024-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleDetails',
        ),
    ]
